using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Text;

namespace Yort.AfterPay.InStore
{
	/// <summary>
	/// Represents a request to the AfterPay API for information about a pre-approval code generated by a customer.
	/// </summary>
	public class AfterPayPreapprovalRequest
	{
		/// <summary>
		/// Sets or returns the pre-approval code from a customer.
		/// </summary>
		/// <seealso cref="AfterPayPreapprovalResponse"/>
		[JsonProperty("preApprovalCode")]
		public string PreapprovalCode { get; set; }
	}
}